# Generated by Django 4.2.16 on 2026-04-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสห้อง')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อห้อง')),
                ('room_type', models.CharField(choices=[('meeting', 'ห้องประชุม'), ('classroom', 'ห้องเรียน')], max_length=20, verbose_name='ประเภท')),
                ('capacity', models.PositiveIntegerField(verbose_name='จำนวนที่นั่ง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'ห้อง',
                'verbose_name_plural': 'ห้อง',
                'ordering': ['code'],
            },
        ),
    ]
