# Generated by Django 4.2.16 on 2026-04-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='ชื่อผู้ใช้')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อ-นามสกุล')),
                ('role', models.CharField(choices=[('lecturer', 'อาจารย์'), ('admin', 'ผู้ดูแลระบบ')], default='lecturer', max_length=20, verbose_name='บทบาท')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้',
                'verbose_name_plural': 'ผู้ใช้',
            },
        ),
    ]
