# Generated by Django 5.2.7 on 2026-05-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='LINE User ID'),
        ),
    ]
