# Generated by Django 4.2.16 on 2026-04-19 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'กลุ่มการจองซ้ำ',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_type', models.CharField(choices=[('teaching', 'สอนปกติ/ชดเชย/เสริม'), ('training', 'จัดอบรม/จัดติว')], max_length=20, verbose_name='วัตถุประสงค์')),
                ('course_code', models.CharField(blank=True, max_length=20, verbose_name='รหัสวิชา')),
                ('course_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อวิชา')),
                ('program', models.CharField(blank=True, choices=[('bachelor', 'ปริญญาตรีภาคปกติ'), ('master', 'ปริญญาโท'), ('tep', 'TEP-TEPE'), ('tupine', 'TU-PINE')], max_length=20, verbose_name='หลักสูตร')),
                ('event_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อเรื่อง')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('status', models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='เหตุผลที่ปฏิเสธ')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง')),
                ('recurring_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.recurringgroup')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room', verbose_name='ห้อง')),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจอง',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
